baseURL = "https://blog.cedriccharly.com/"
languageCode = "en-us"
title = "Cedric Charly"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
title = "Cedric Charly"
description = "Writing about infrastructure, configuration, and cloud computing"
author = "Cedric Charly"
mainSections = ["post"]

defaultTheme = "auto"
disableThemeToggle = false
showReadingTime = true
showShareButtons = false
showPostNavLinks = true
showBreadCrumbs = true
showCodeCopyButtons = true
showRssButtonInSectionTermList = true
UseHugoToc = true
disableScrollToTop = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[params.homeInfoParams]
Title = "Cedric Charly"
Content = "Writing about infrastructure, configuration management, and cloud computing."

[[params.socialIcons]]
name = "github"
url = "https://github.com/cedricgc"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/cedricgc"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/cedric-charly-8143a15a/"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"

[menu]
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/post/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 30

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNos = false
lineNoStart = 1
lineNumbersInTable = true
noClasses = true
noHl = false
style = "dracula"
tabWidth = 4
